jwt:
  get:
    token:
      uri: /authenticate
  secret: random-secret-123

server:
  error:
    include-stacktrace: never
  port: 8008

spring:
  application:
    name: authorization-service
  datasource:
    platform: h2
    url: jdbc:h2:mem:mfpe
  h2:
    console:
      enabled: true

zuul:
  routes:
    product-services:
      path: /products/**
      service-id: product-service
      strip-prefix: false

    cart-services:
      path: /cart/**
      service-id: cart-service
      strip-prefix: false
      
    


eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 20
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
